Better error reporting.
LegionPE/LegionPE-Theta-Base pull request #14
Opened 2016-08-29 12:46 UTC by PrimusLV

2016-08-31 19:20 UTC, PrimusLV commented on src/legionpe/theta/utils/ReportErrorTask.php
>  		echo $line, PHP_EOL;
I don't see any use in this

2016-09-17 04:06 UTC, SOF3 commented
@PrimusLV improve your wiki edit. We could even use it to create an automatic installer ;)

2016-09-18 03:18 UTC, SOF3 commented
@PrimusLV but why use `TEXT` instead of `VARCHAR(32767)`?

And, skin1 and skin2 are binary according to https://github.com/LegionPE/LegionPE-Theta-Base/blob/master/src/legionpe/theta/query/SaveSinglePlayerQuery.php#L66

2016-09-18 03:21 UTC, SOF3 commented on src/legionpe/theta/utils/ReportErrorTask.php
> +		$message .= "UNIX Timestamp: " . $this->when.PHP_EOL;
`$this->when` is a string condition, such as `"Executing command /hub"`.

2016-09-18 03:21 UTC, SOF3 commented on src/legionpe/theta/utils/ReportErrorTask.php
> +		$message .= "Time: ".date("H:i:s", $this->when).PHP_EOL;
So remove this line as well.

2016-09-18 03:22 UTC, SOF3 commented on src/legionpe/theta/utils/ReportErrorTask.php
> -		self::log("ping-all !!! PEMapModder ping!");
Well xD This was supposed to notify PEMapModder on IRC, but this won't happen anymore ;)

2016-09-18 03:24 UTC, SOF3 commented on src/legionpe/theta/utils/ReportErrorTask.php
> +		$message = "=== ERROR BEGIN ===".PHP_EOL;
I doubt if you can use PHP_EOL with @TkTech's notifico directly. IRC messages are supposed to be one-liners.

2016-09-18 03:25 UTC, SOF3 commented on src/legionpe/theta/utils/ReportErrorTask.php
> -		Utils::getURL(Credentials::IRC_WEBHOOK_NOPREFIX . urlencode("BotsHateNames: status " . Settings::$LOCALIZE_IP . " " . Settings::$LOCALIZE_PORT));
@BotsHateNames was supposed to be a bot that shows this server's status ;)

2016-09-18 03:25 UTC, SOF3 requested changes
Check out how this class was constructed first ;)

2016-09-18 03:27 UTC, SOF3 commented on src/legionpe/theta/utils/ReportErrorTask.php
> +			]);
But we don't have such channel on Slack :P

2016-09-18 04:06 UTC, TkTech commented on src/legionpe/theta/utils/ReportErrorTask.php
> +		$message = "=== ERROR BEGIN ===".PHP_EOL;
If you're using plain-text hooks it'll just be converted into one message per newline, subject to the normal rate limiting.

2016-09-18 04:07 UTC, SOF3 commented on src/legionpe/theta/utils/ReportErrorTask.php
> +		$message = "=== ERROR BEGIN ===".PHP_EOL;
@TkTech thanks!

2016-09-18 10:58 UTC, PrimusLV commented on src/legionpe/theta/utils/ReportErrorTask.php
> +			]);
Shame on you @PrimusLV :D

2016-09-18 11:04 UTC, PrimusLV commented on src/legionpe/theta/utils/ReportErrorTask.php
> -		self::log("ping-all !!! PEMapModder ping!");
Indeed :(

2016-09-18 11:05 UTC, PrimusLV commented on src/legionpe/theta/utils/ReportErrorTask.php
> -		Utils::getURL(Credentials::IRC_WEBHOOK_NOPREFIX . urlencode("BotsHateNames: status " . Settings::$LOCALIZE_IP . " " . Settings::$LOCALIZE_PORT));
I'll restore it right away

2016-09-18 11:06 UTC, PrimusLV commented on src/legionpe/theta/utils/ReportErrorTask.php
> +		foreach($lines as $line) self::log($line);
Sending single lines without line breaks.

2016-09-18 11:06 UTC, SOF3 approved these changes

2016-09-18 11:06 UTC, merged